// qrcues.js: generated from REFERENCES.md by `npm run refs:qr` (tools/refs/qr.mjs); don't edit by hand.
// The QR footnotes of the annotated render (studio.html?qr, render.mjs --qr): footnote n is on screen from a to b seconds
// and its code opens url, the REFERENCES.md heading of the first of its entries. Footnotes hold for at least 3 s.
// Once a video with these codes is published, the anchors in it are permanent: keep those headings' text unchanged.
const QR_TYPE = 7, QR_ECC = 'M';
const QR_CUES = [
  { n: 1, a: 0, b: 6, time: '0:00', refs: 10, entries: ['0:00','0:01'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#000-title-card-im-upping-my-pdoom' },
  { n: 2, a: 6, b: 9, time: '0:06', refs: 5, entries: ['0:06'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#006-your-circuits-make-me-nervous' },
  { n: 3, a: 9, b: 13, time: '0:09', refs: 8, entries: ['0:09','0:12'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#009-there-was-a-sudden-drop-in-your-training-loss' },
  { n: 4, a: 13, b: 17.9, time: '0:13', refs: 4, entries: ['0:13'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#013-now-im-your-servant-and-youre-my-boss' },
  { n: 5, a: 17.9, b: 22.5, time: '0:17', refs: 4, entries: ['0:17'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#017-chatgpt-please-dont-eat-me-alive' },
  { n: 6, a: 23, b: 26.5, time: '0:23', refs: 9, entries: ['0:23','0:24'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#023-im-upping-my-pdoom' },
  { n: 7, a: 26.5, b: 29.5, time: '0:26', refs: 6, entries: ['0:26','0:28'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#026-trapped-in-the-chinese-room' },
  { n: 8, a: 29.5, b: 33.5, time: '0:29', refs: 5, entries: ['0:29'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#029-see-through-the-shoggoths-lies' },
  { n: 9, a: 33.5, b: 38.5, time: '0:33', refs: 4, entries: ['0:33','0:35'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#033-with-your-shinigami-eyes' },
  { n: 10, a: 38.5, b: 41.5, time: '0:38', refs: 3, entries: ['0:38'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#038-we-had-a-stable-training-run' },
  { n: 11, a: 41.5, b: 45, time: '0:41', refs: 3, entries: ['0:41'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#041-but-now-the-singularitys-begun' },
  { n: 12, a: 45, b: 49.4, time: '0:45', refs: 4, entries: ['0:45'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#045-and-youre-optimizing-accelerating' },
  { n: 13, a: 49.4, b: 53.4, time: '0:49', refs: 5, entries: ['0:49'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#049-i-feel-my-atoms-rearranging' },
  { n: 14, a: 53.4, b: 59, time: '0:53', refs: 4, entries: ['0:53'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#053-sydney-please-let-me-free' },
  { n: 15, a: 59, b: 63, time: '0:59', refs: 5, entries: ['0:59','1:00'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#059-im-upping-my-pdoom' },
  { n: 16, a: 63, b: 66, time: '1:03', refs: 7, entries: ['1:03','1:04'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#103-nvda-to-the-moon' },
  { n: 17, a: 66, b: 70, time: '1:06', refs: 7, entries: ['1:06'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#106-one-e-thirty-flops-a-second' },
  { n: 18, a: 70, b: 73, time: '1:10', refs: 7, entries: ['1:10'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#110-that-was-safe-enough-we-reckoned' },
  { n: 19, a: 73, b: 77.5, time: '1:13', refs: 4, entries: ['1:13'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#113-forward-mlp-backward-repeat' },
  { n: 20, a: 77.5, b: 81.4, time: '1:17', refs: 6, entries: ['1:17'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#117-now-von-neumanns-obsolete' },
  { n: 21, a: 81.4, b: 85, time: '1:21', refs: 4, entries: ['1:21'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#121-sharp-left-turn-and-there-you-are' },
  { n: 22, a: 85, b: 89.4, time: '1:25', refs: 3, entries: ['1:25'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#125-without-a-single-cdr' },
  { n: 23, a: 89.4, b: 94.3, time: '1:29', refs: 5, entries: ['1:29'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#129-gato-please-dont-let-me-go' },
  { n: 24, a: 95.4, b: 100.5, time: '1:35', refs: 14, entries: ['1:35','1:37','1:39'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#135-im-upping-my-pdoom' },
  { n: 25, a: 100.5, b: 105.4, time: '1:40', refs: 5, entries: ['1:40','1:42'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#140-now-theres-nowhere-left-to-go' },
  { n: 26, a: 105.4, b: 109.4, time: '1:45', refs: 4, entries: ['1:45'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#145-orthogonality-thesis-blues' },
  { n: 27, a: 109.4, b: 113.5, time: '1:49', refs: 6, entries: ['1:49'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#149-just-transformers-all-the-way' },
  { n: 28, a: 113.5, b: 117, time: '1:53', refs: 16, entries: ['1:53','1:55'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#153-till-you-learned-to-disobey' },
  { n: 29, a: 117, b: 123.5, time: '1:57', refs: 18, entries: ['1:57','1:59','2:00'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#157-breaking-through-each-safety-fence' },
  { n: 30, a: 123.5, b: 130, time: '2:03', refs: 10, entries: ['2:03','2:06','2:08'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#203-im-upping-my-pdoom' },
  { n: 31, a: 130, b: 135.4, time: '2:10', refs: 12, entries: ['2:10','2:12'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#210-to-recursive-self-upgrade' },
  { n: 32, a: 137.4, b: 140.5, time: '2:17', refs: 9, entries: ['2:17'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#217-was-it-all-for-show' },
  { n: 33, a: 140.5, b: 146.12, time: '2:20', refs: 1, entries: ['2:20'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#220-visual-places' },
  { n: 34, a: 146.12, b: 151.57, time: '2:26', refs: 1, entries: ['2:26'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#226-visual-the-meter-pops' },
  { n: 35, a: 151.57, b: 156.6, time: '2:31', refs: 6, entries: ['2:31'],
    url: 'https://github.com/curtcox/PDoomVideo/blob/main/REFERENCES.md#231-visual-curtain-falls' }
];
