// qrtag.js: QR footnote tags for the annotated render (studio.html?qr, render.mjs --qr). Off in the normal video.
// The cues come from src/qrcues.js (generated by `npm run refs:qr`). Each footnote is a paper tag taped to the right edge,
// between the corner P(doom) meter and the karaoke bar. It drops in when its footnote starts and slides off before the next.
// The card, tape and label are painted with the scene (qrTag, called after the karaoke bar). The code itself is drawn crisp,
// ink on cream, on the compositor after the paper grain (drawQRCode), so neither the grain nor the brush boil touches it.
const QR_ON = /[?&]qr(&|=|$)/.test(location.search);
const QR_MOD = 5, QR_QUIET = 2;         // px per module; quiet-zone modules on the crisp patch (the cream card adds more)
const QR_PAD = 16, QR_LABEL = 84;       // card margin around the patch; label strip under it
const QR_X = 1742, QR_Y = 735;          // resting centre of the tag
const QR_MATS = new Map();

const qrCueAt = t => QR_ON && !window.LOOP ? QR_CUES.find(c => t >= c.a && t < c.b) : null;
function qrMatrix(c) {
  if (!QR_MATS.has(c.n)) { const q = qrcode(QR_TYPE, QR_ECC); q.addData(c.url); q.make(); QR_MATS.set(c.n, { n: q.getModuleCount(), dark: (r, k) => q.isDark(r, k) }); }
  return QR_MATS.get(c.n);
}
function qrLayout(c) {
  const P = (qrMatrix(c).n + 2 * QR_QUIET) * QR_MOD, w = P + 2 * QR_PAD, h = QR_PAD + P + QR_LABEL;
  return { P, w, h, top: -h / 2 + QR_PAD };
}
// The tag at time t: drops in with an overshoot, nods on the beat, slides off to the right in the footnote's last moment.
// Each footnote rests at its own slight tilt so consecutive tags read as new cards, not a flicker.
function qrPose(c, t) {
  const lt = t - c.a, k = backOut(lt / .45), out = easeIn(seg(t, c.b - .3, c.b)), nod = pulse(t, 5);
  return {
    x: QR_X + out * 460, y: QR_Y - (1 - easeOut(lt / .4)) * 180,
    rot: -.04 + (hash(c.n) - .5) * .05 + (1 - k) * .3 + out * .3 + .006 * nod,
    s: lerp(.5, 1, k) * (1 + .01 * nod)
  };
}

function qrTag(t) {
  const c = qrCueAt(t); if (!c) return;
  const { w, h } = qrLayout(c), p = qrPose(c, t);
  push(); translate(p.x, p.y); rotate(p.rot); scale(p.s);
  paint(rrPts(-w / 2 + 10, -h / 2 + 14, w, h, 14, 2), { wash: PAL.ink, washOp: 55, ink: null });
  paint(rrPts(-w / 2, -h / 2, w, h, 14, 2.5), { wash: PAL.cream, washOp: 255, fill: PAL.ochre, fillOp: 50, bleed: .06, tex: .55, border: .75, ink: PAL.ink, sw: .9, br: 'inkfine' });
  paint(rrPts(-w / 2 + 12, h / 2 - QR_LABEL + 4, w - 24, QR_LABEL - 16, 10, 2), { wash: PAL.clayLt, washOp: 90, fill: PAL.clay, fillOp: 40, bleed: .08, tex: .6, ink: null });
  // a strip of washi tape over the top edge
  push(); translate(-w * .18, -h / 2 + 2); rotate(-.2 + (hash(c.n + 7) - .5) * .12);
  paint(rectPts(-58, -18, 116, 36, 2), { wash: PAL.rose, washOp: 175, fill: PAL.rose, fillOp: 80, bleed: .04, tex: .7, border: .5, ink: null,
    hatch: { d: 14, a: 1.2, o: { rand: .3 }, b: 'HB', c: PAL.cream, w: .6 } });
  pop();
  pop();
  // letters are placed in screen space, so carry the label through the tag's pose by hand
  const at = (lx, ly) => [p.x + (lx * Math.cos(p.rot) - ly * Math.sin(p.rot)) * p.s, p.y + (lx * Math.sin(p.rot) + ly * Math.cos(p.rot)) * p.s];
  const [fx, fy] = at(0, h / 2 - 58), [sx, sy] = at(0, h / 2 - 27), fs = 19 * p.s;
  letter(`FOOTNOTE ${c.n}`, fx, fy, 32 * p.s, PAL.clayDk, { rot: p.rot, ink: false });
  letter(`${c.time} · ${c.refs} source${c.refs === 1 ? '' : 's'}`, sx, sy, fs, PAL.ink, { rot: p.rot, ink: false, font: `800 ${fs}px "Shantell Sans", sans-serif` });
}

// The code, on the 2D compositor after the grain: one crisp path of square modules, with rounded finder eyes.
function drawQRCode(c2, t) {
  const c = qrCueAt(t); if (!c) return;
  const { n, dark } = qrMatrix(c), { P, top } = qrLayout(c), p = qrPose(c, t), m = QR_MOD;
  const x0 = -P / 2 + QR_QUIET * m, y0 = top + QR_QUIET * m;
  const eye = (r, k) => (r < 7 || r >= n - 7) && (k < 7 || k >= n - 7) && !(r >= n - 7 && k >= n - 7);
  c2.save(); c2.translate(p.x, p.y); c2.rotate(p.rot); c2.scale(p.s, p.s);
  c2.fillStyle = PAL.cream; c2.beginPath(); c2.roundRect(-P / 2, top, P, P, 8); c2.fill();
  const mods = new Path2D();
  for (let r = 0; r < n; r++) for (let k = 0; k < n; k++) if (dark(r, k) && !eye(r, k)) mods.rect(x0 + k * m, y0 + r * m, m, m);
  c2.fillStyle = PAL.ink; c2.fill(mods);
  for (const [r, k] of [[0, 0], [0, n - 7], [n - 7, 0]]) {
    const ex = x0 + k * m, ey = y0 + r * m, ring = new Path2D();
    ring.roundRect(ex, ey, 7 * m, 7 * m, 1.8 * m); ring.roundRect(ex + m, ey + m, 5 * m, 5 * m, 1.1 * m);
    c2.fillStyle = PAL.ink; c2.fill(ring, 'evenodd');
    c2.fillStyle = PAL.ink; c2.beginPath(); c2.roundRect(ex + 2 * m, ey + 2 * m, 3 * m, 3 * m, .9 * m); c2.fill();
  }
  c2.restore();
}
